//
//  Mixpanel+Muzzley.h
//  Muzzley-iOS
//
//  Created by Hugo Sousa on 17/8/15.
//  Copyright (c) 2015 Muzzley. All rights reserved.
//

#import "Mixpanel.h"

#pragma mark - Mixpanel Tags
#pragma mark - Lifecycle

extern NSString *const MIXPANEL_EVENT_START_APP;
extern NSString *const MIXPANEL_EVENT_EXIT_APP;
extern NSString *const MIXPANEL_EVENT_NAVIGATE_TO;

extern NSString *const MIXPANEL_EVENT_FORCE_UPDATE_SHOW;
extern NSString *const MIXPANEL_EVENT_FORCE_UPDATE_REDIRECT_STORE;


#pragma mark - Authentication

extern NSString *const MIXPANEL_EVENT_SIGN_IN_START;
extern NSString *const MIXPANEL_EVENT_SIGN_IN_FINISH;

extern NSString *const MIXPANEL_EVENT_SIGN_UP_START;
extern NSString *const MIXPANEL_EVENT_SIGN_UP_FINISH;

extern NSString *const MIXPANEL_EVENT_SIGN_OUT;

#pragma mark Forgot Password

extern NSString *const MIXPANEL_EVENT_FORGOT_PASSWORD_START;
extern NSString *const MIXPANEL_EVENT_FORGOT_PASSWORD_REQUEST_FINISH;


#pragma mark - Devices

extern NSString *const MIXPANEL_EVENT_MANUAL_INTERACTION;

#pragma mark Add Device

extern NSString *const MIXPANEL_EVENT_ADD_DEVICE_START;
extern NSString *const MIXPANEL_EVENT_ADD_DEVICE_CANCEL;
extern NSString *const MIXPANEL_EVENT_ADD_DEVICE_SELECT_DEVICE;
extern NSString *const MIXPANEL_EVENT_ADD_DEVICE_SELECT_CHANNEL;
extern NSString *const MIXPANEL_EVENT_ADD_DEVICE_FINISH;

#pragma mark Edit Device

extern NSString *const MIXPANEL_EVENT_EDIT_DEVICE_START;
extern NSString *const MIXPANEL_EVENT_EDIT_DEVICE_FINISH;
extern NSString *const MIXPANEL_EVENT_EDIT_DEVICE_DELETE_CANCEL;
extern NSString *const MIXPANEL_EVENT_EDIT_DEVICE_DELETE_FINISH;

#pragma mark Groups

extern NSString *const MIXPANEL_EVENT_CREATE_GROUP_START;
extern NSString *const MIXPANEL_EVENT_CREATE_GROUP_CANCEL;
extern NSString *const MIXPANEL_EVENT_CREATE_GROUP_FINISH;

extern NSString *const MIXPANEL_EVENT_EDIT_GROUP_START;
extern NSString *const MIXPANEL_EVENT_EDIT_GROUP_CANCEL;
extern NSString *const MIXPANEL_EVENT_EDIT_GROUP_FINISH;
extern NSString *const MIXPANEL_EVENT_EDIT_GROUP_UNGROUP_CANCEL;
extern NSString *const MIXPANEL_EVENT_EDIT_GROUP_UNGROUP_FINISH;


#pragma mark - Routines

extern NSString *const MIXPANEL_EVENT_ENABLE_ROUTINE;
extern NSString *const MIXPANEL_EVENT_DISABLE_ROUTINE;

extern NSString *const MIXPANEL_EVENT_REMOVE_ROUTINE_START;
extern NSString *const MIXPANEL_EVENT_REMOVE_ROUTINE_CANCEL;
extern NSString *const MIXPANEL_EVENT_REMOVE_ROUTINE_FINISH;

extern NSString *const MIXPANEL_EVENT_EXECUTE_ROUTINE;

#pragma mark Add Routine

extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_START;
extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_CANCEL;
extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_FINISH;

extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_ADD_TRIGGER_START;
extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_ADD_TRIGGER_FINISH;
//extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_EDIT_TRIGGER_START;
//extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_EDIT_TRIGGER_FINISH;
extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_DELETE_TRIGGER_FINISH;

extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_ADD_ACTION_START;
extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_ADD_ACTION_FINISH;
//extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_EDIT_ACTION_START;
//extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_EDIT_ACTION_FINISH;
extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_DELETE_ACTION_FINISH;
extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_DELETE_RULE_ACTION_FINISH;

extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_ADD_STATE_START;
extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_ADD_STATE_FINISH;
//extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_EDIT_STATE_START;
//extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_EDIT_STATE_FINISH;
extern NSString *const MIXPANEL_EVENT_CREATE_ROUTINE_DELETE_STATE_FINISH;

#pragma mark Edit Routine

extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_START;
extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_CANCEL;
extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_FINISH;

extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_ADD_TRIGGER_START;
extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_ADD_TRIGGER_FINISH;
//extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_EDIT_TRIGGER_START;
//extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_EDIT_TRIGGER_FINISH;
extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_DELETE_TRIGGER_FINISH;

extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_ADD_ACTION_START;
extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_ADD_ACTION_FINISH;
//extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_EDIT_ACTION_START;
//extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_EDIT_ACTION_FINISH;
extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_DELETE_ACTION_FINISH;
extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_DELETE_RULE_ACTION_FINISH;

extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_ADD_STATE_START;
extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_ADD_STATE_FINISH;
//extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_EDIT_STATE_START;
//extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_EDIT_STATE_FINISH;
extern NSString *const MIXPANEL_EVENT_EDIT_ROUTINE_DELETE_STATE_FINISH;


#pragma mark - Shortcuts

extern NSString *const MIXPANEL_EVENT_EXECUTE_SHORTCUT;

#pragma mark Add Shortcut

extern NSString *const MIXPANEL_EVENT_CREATE_SHORTCUT_START;
extern NSString *const MIXPANEL_EVENT_CREATE_SHORTCUT_CANCEL;
extern NSString *const MIXPANEL_EVENT_CREATE_SHORTCUT_FINISH;

extern NSString *const MIXPANEL_EVENT_CREATE_SHORTCUT_ADD_ACTION_START;
extern NSString *const MIXPANEL_EVENT_CREATE_SHORTCUT_ADD_ACTION_FINISH;
//extern NSString *const MIXPANEL_EVENT_CREATE_SHORTCUT_EDIT_ACTION_START;
//extern NSString *const MIXPANEL_EVENT_CREATE_SHORTCUT_EDIT_ACTION_FINISH;
extern NSString *const MIXPANEL_EVENT_CREATE_SHORTCUT_DELETE_ACTION_FINISH;
extern NSString *const MIXPANEL_EVENT_CREATE_SHORTCUT_DELETE_RULE_ACTION_FINISH;

#pragma mark Edit Shortcuts

extern NSString *const MIXPANEL_EVENT_EDIT_SHORTCUT_START;
extern NSString *const MIXPANEL_EVENT_EDIT_SHORTCUT_CANCEL;
extern NSString *const MIXPANEL_EVENT_EDIT_SHORTCUT_FINISH;

extern NSString *const MIXPANEL_EVENT_EDIT_SHORTCUT_ADD_ACTION_START;
extern NSString *const MIXPANEL_EVENT_EDIT_SHORTCUT_ADD_ACTION_FINISH;
//extern NSString *const MIXPANEL_EVENT_EDIT_SHORTCUT_EDIT_ACTION_START;
//extern NSString *const MIXPANEL_EVENT_EDIT_SHORTCUT_EDIT_ACTION_FINISH;
extern NSString *const MIXPANEL_EVENT_EDIT_SHORTCUT_DELETE_ACTION_FINISH;
extern NSString *const MIXPANEL_EVENT_EDIT_SHORTCUT_DELETE_RULE_ACTION_FINISH;

#pragma mark Remove Shortcuts

extern NSString *const MIXPANEL_EVENT_REMOVE_SHORTCUT_START;
extern NSString *const MIXPANEL_EVENT_REMOVE_SHORTCUT_CANCEL;
extern NSString *const MIXPANEL_EVENT_REMOVE_SHORTCUT_FINISH;


#pragma mark - Suggestions

extern NSString *const MIXPANEL_EVENT_SUGGESTION_VIEW;
extern NSString *const MIXPANEL_EVENT_SUGGESTION_USER_ENGAGE;
extern NSString *const MIXPANEL_EVENT_SUGGESTION_FINISH;
extern NSString *const MIXPANEL_EVENT_SUGGESTION_HIDE;


#pragma mark - User Profile
#pragma mark Feedback

extern NSString *const MIXPANEL_EVENT_FEEDBACK_START;
extern NSString *const MIXPANEL_EVENT_FEEDBACK_FINISH;

#pragma mark About

extern NSString *const MIXPANEL_EVENT_ABOUT_VIEW;


#pragma mark - Mixpanel Properties

extern NSString *const MIXPANEL_PROPERTY_APPLICATION;
extern NSString *const MIXPANEL_PROPERTY_USER_ID;
extern NSString *const MIXPANEL_PROPERTY_USER_NAME;
extern NSString *const MIXPANEL_PROPERTY_USER_EMAIL;
extern NSString *const MIXPANEL_PROPERTY_STATUS;
extern NSString *const MIXPANEL_PROPERTY_DETAIL;
extern NSString *const MIXPANEL_PROPERTY_PROFILE_ID;
//extern NSString *const MIXPANEL_PROPERTY_PROFILE_NAME;
extern NSString *const MIXPANEL_PROPERTY_DEVICE_NAME;
extern NSString *const MIXPANEL_PROPERTY_COMPONENT_NAME;
extern NSString *const MIXPANEL_PROPERTY_CHANNEL_ID;
extern NSString *const MIXPANEL_PROPERTY_CHANNEL_NAME;
//extern NSString *const MIXPANEL_PROPERTY_TRIGGER;
//extern NSString *const MIXPANEL_PROPERTY_ACTION;
//extern NSString *const MIXPANEL_PROPERTY_STATE;
extern NSString *const MIXPANEL_PROPERTY_ROUTINE_ID;
extern NSString *const MIXPANEL_PROPERTY_SOURCE;
extern NSString *const MIXPANEL_PROPERTY_WHERE;
extern NSString *const MIXPANEL_PROPERTY_GROUP_ID;
extern NSString *const MIXPANEL_PROPERTY_INTERACTION_SOURCE;
extern NSString *const MIXPANEL_PROPERTY_INTERACTION_VIEW;
extern NSString *const MIXPANEL_PROPERTY_GROUP_COUNT;
extern NSString *const MIXPANEL_PROPERTY_INTERACTION_PROPERTY;
extern NSString *const MIXPANEL_PROPERTY_PLATFORM;
extern NSString *const MIXPANEL_PROPERTY_SCREEN;
extern NSString *const MIXPANEL_PROPERTY_TYPE;
extern NSString *const MIXPANEL_PROPERTY_SHORTCUT_ID;
//extern NSString *const MIXPANEL_PROPERTY_SHORTCUT_AVAILABLE_ON;
extern NSString *const MIXPANEL_PROPERTY_SHORTCUT_WHERE;
extern NSString *const MIXPANEL_PROPERTY_SHORTCUT_SOURCE;
extern NSString *const MIXPANEL_PROPERTY_SUGGESTION_ID;
extern NSString *const MIXPANEL_PROPERTY_CLASS;
extern NSString *const MIXPANEL_PROPERTY_ACTION_TYPE;
extern NSString *const MIXPANEL_PROPERTY_STAGE_INDEX;
extern NSString *const MIXPANEL_PROPERTY_VALUE;
extern NSString *const MIXPANEL_PROPERTY_QUESTION_ID;
extern NSString *const MIXPANEL_PROPERTY_OPTION_ID;

#pragma mark - Mixpanel Values

extern NSString *const MIXPANEL_VALUE_ERROR;
extern NSString *const MIXPANEL_VALUE_SUCCESS;
extern NSString *const MIXPANEL_VALUE_EMAIL;
extern NSString *const MIXPANEL_VALUE_FACEBOOK;
extern NSString *const MIXPANEL_VALUE_GOOGLE;
extern NSString *const MIXPANEL_VALUE_TILE;
extern NSString *const MIXPANEL_VALUE_ADVANCE_INTERFACE;
extern NSString *const MIXPANEL_VALUE_GROUP;
extern NSString *const MIXPANEL_VALUE_INDIVIDUAL;
extern NSString *const MIXPANEL_VALUE_MANUAL;
extern NSString *const MIXPANEL_VALUE_SUGGESTION;
extern NSString *const MIXPANEL_VALUE_CONTEXTUAL;
extern NSString *const MIXPANEL_VALUE_APP;

@interface Mixpanel (Muzzley)

@end
